name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
main: ${mainClass}
commands:
   class:
      description: Opens the Class selector menu
      permission: fbmcctf.kit
      permission-message: You don't have permission to run this command!
   mode:
      description: Set the gamemode type, "ctf" for ctf and "soup" for soup
      permission: fbmcctf.manager
      permission-message: You don't have permission to run this command! You must be a manager!
permissions:
   fbmcctf.build:
      description: Allows someone to place and destroy blocks
      default: false
   fbmcctf.play:
      description: Allows a player to play all aspects of the game
      default: false
   fbmcctf.kit:
      description: Allows you to open the kit menu and select a kit
      default: false
   fbmcctf.manager:
      description: Gives permissions to manage gamemodes
      default: false